# Name
name: CI and Testing

# Trigger
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

        # Test command for backend
      - name: Run backend tests
        working-directory: backend
        run: npm test

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

        # Test command for frontend
      - name: Run frontend tests
        working-directory: frontend
        run: npm test
